
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ep7_2(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);


wire [7:0] a, b, c;
//=======================================================
//  REG/WIRE declarations
//=======================================================

v_rams_8 vm(CLOCK_50, KEY[0], SW[9:6], SW[5:2], {6'b000000, SW[1:0]}, a, b, c);


//=======================================================
//  Structural coding
//=======================================================



endmodule
