
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ep7(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);

	wire clock_1s;
	wire [7:0] out;
	assign HEX2 = 7'b1111111;
	assign HEX3 = 7'b1111111;
//=======================================================
//  REG/WIRE declarations
//=======================================================

	my_clock clock(CLOCK_50, clk_1s);
	my_hex h1(out[7:4], HEX5);
	my_hex h0(out[3:0], HEX4);
	RAM_1 ram1(SW[1:0], SW[5:2], SW[9:6], KEY[0], CLOCK_50, HEX1, HEX0);
	RAM_2 ram2(.clock(clk_1s), .data(SW[1:0]), .rdaddress(SW[9:6]), .wraddress(SW[5:2]), .wren(KEY[0]), .q(out));

//=======================================================
//  Structural coding
//=======================================================



endmodule
