
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ep6_2(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

//assign HEX2[6:0] = 7'b1111111;
assign HEX3[6:0] = 7'b1111111;
assign HEX4[6:0] = 7'b1111111;
assign HEX5[6:0] = 7'b1111111;

LFSR my_lfsr(CLOCK_50, HEX0, HEX1);


//=======================================================
//  Structural coding
//=======================================================



endmodule
